Plugin 'altercation/vim-colors-solarized.git'
Plugin 'bling/vim-airline.git'
Plugin 'Lokaltog/vim-easymotion.git'
Plugin 'majutsushi/tagbar.git'
Plugin 'mustache/vim-mustache-handlebars'
Plugin 'Raimondi/delimitMate.git'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'scrooloose/nerdtree.git'
" Plugin 'scrooloose/syntastic.git'
Plugin 'sjl/gundo.vim.git'
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-surround.git'
